source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

use_frameworks!
inhibit_all_warnings!

target 'ZipCodeAPISearch_Example' do
  pod 'ZipCodeAPISearch', '0.1.0'
  
  # https://github.com/Alamofire/Alamofire
  pod 'Alamofire', ‘4.3.0’
  
  # https://github.com/hkellaway/Gloss
  pod 'Gloss', ‘1.2.0’

  target 'ZipCodeAPISearch_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
